FROM ubuntu:20.04 as install

WORKDIR /var/www/html
USER root
# -----install php8-----------
RUN apt update
RUN apt -y upgrade
RUN apt install -y lsb-release ca-certificates apt-transport-https software-properties-common -y
RUN add-apt-repository ppa:ondrej/php
RUN apt install -y debian-keyring debian-archive-keyring apt-transport-https
RUN apt -y install PHP8.1 php-xml
RUN apt install -y PHP8.1-amqp PHP8.1-common PHP8.1-gd PHP8.1-ldap PHP8.1-odbc PHP8.1-readline PHP8.1-sqlite3 PHP8.1-xsl PHP8.1-apcu PHP8.1-curl PHP8.1-gmp PHP8.1-opcache PHP8.1-redis PHP8.1-mbstring PHP8.1-pgsql PHP8.1-yaml PHP8.1-dev PHP8.1-imagick PHP8.1-memcached PHP8.1-uuid PHP8.1-zip PHP8.1-bz2 PHP8.1-zmq PHP8.1-interbase PHP8.1-mysql PHP8.1-soap PHP8.1-cli PHP8.1-fpm PHP8.1-intl PHP8.1-oauth PHP8.1-xml PHP8.1-mongodb
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
COPY deploy/dev58/www.conf /etc/php/8.0/fpm/pool.d/www.conf

RUN apt-get update -qq
RUN apt-get install -qq -y curl gnupg
RUN echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main" > /etc/apt/sources.list.d/mssql.list
RUN curl -sS https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN apt-get update -qq
RUN ACCEPT_EULA=Y apt-get install -qq -y mssql-tools unixodbc PHP8.1-sybase
RUN apt install -y unixodbc-dev php-pear PHP8.1-dev
RUN apt install -y gcc g++ build-essential
RUN pecl channel-update pecl.php.net
RUN pecl -q install sqlsrv pdo_sqlsrv
RUN echo "extension=pdo_sqlsrv.so" > /etc/php/8.1/mods-available/pdo_sqlsrv.ini
RUN echo "extension=sqlsrv.so" > /etc/php/8.1/mods-available/sqlsrv.ini
RUN phpenmod pdo_sqlsrv sqlsrv

# ----- Install Caddy --------
RUN curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | apt-key add -
RUN curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
RUN apt update
RUN apt install caddy
RUN caddy version
RUN setcap 'cap_net_bind_service=+ep' /usr/bin/caddy
COPY deploy/dev58/config /etc/php/8.1/fpm/conf.d

# COPY application /var/www/html/application
# COPY assets /var/www/html/assets
# COPY src /var/www/html/src
# COPY system /var/www/html/system
# COPY index.php /var/www/html/index.php
# COPY .htaccess /var/www/html/.htaccess

RUN mkdir /run/php
COPY deploy/dev58/Caddyfile /etc/caddy/
COPY deploy/dev58/php-caddy-entrypoint /usr/local/bin/
RUN chmod +x /usr/local/bin/php-caddy-entrypoint

RUN apt install curl wget net-tools iputils-ping  -y

# RUN apt install -y net-tools
# RUN pear clear-cache
# RUN apt-get purge -qq --autoremove -y curl gnupg unixodbc-dev php-pear PHP8.1-dev gcc g++ build-essential
# RUN apt-get autoremove -qq -y
# RUN apt-get autoclean -qq
# RUN apt-get clean -qq
# RUN rm -rf /var/lib/{apt,dpkg,cache,log}/
# RUN rm -rf /build /tmp/* /usr/share/php/docs /usr/share/php/tests
# RUN find /root /var/lib/apt/lists /usr/share/man /usr/share/doc /var/cache /var/log -type f -delete
RUN apt-get clean autoclean
RUN apt-get autoremove --yes
RUN rm -rf /var/lib/{apt,dpkg,cache,log}/

EXPOSE 8080
ENTRYPOINT ["php-caddy-entrypoint"]
CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
# CMD ["sleep","8000"]